require("telescope").setup({})

local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>fk", builtin.keymaps, { desc = "Telescope key maps" })
vim.keymap.set("n", "<leader>fs", builtin.builtin, { desc = "Telescope builtin" })
vim.keymap.set({ "n", "v" }, "<leader>fw", builtin.grep_string, { desc = "Telescope grep string" })
vim.keymap.set("n", "<leader>fd", builtin.diagnostics, { desc = "Telescope diagnostics" })
vim.keymap.set("n", "<leader>fr", builtin.resume, { desc = "Telescope resume" })
vim.keymap.set("n", "<leader>f.", builtin.oldfiles, { desc = "Telescope old files" })
vim.keymap.set("n", "<leader>fc", builtin.commands, { desc = "Telescope commands" })
